import { ArrowDown, BookOpenText, ClipboardText, FileText, ListChecks } from "@phosphor-icons/react/dist/ssr";
import { getPublicResources } from "@/lib/public-content";
import { SiteHeader } from "@/components/public/site-header";
import { SiteFooter } from "@/components/public/site-footer";
import { PageHero } from "@/components/public/page-hero";

export const revalidate = 300;

const icons: Record<string, typeof FileText>={TEMPLATE:FileText,EBOOK:BookOpenText,GUIDE:ListChecks,CHECKLIST:ClipboardText};
async function getResources(){return getPublicResources()}
export default async function ResourcesPage(){const resources=await getResources();return <div className="min-h-screen bg-background"><SiteHeader active="resources"/><main id="main-content"><PageHero eyebrow="Resources" title="Alat bantu untuk mengambil keputusan digital yang lebih jernih." description="Template, checklist, dan panduan praktis yang kami gunakan untuk merancang project bersama partner."/><section className="py-24 sm:py-32"><div className="container-wide">{resources.length===0?<div className="grid gap-px overflow-hidden rounded-2xl border border-emerald-950/10 bg-emerald-950/10 md:grid-cols-3">{[[FileText,"Project brief","Susun konteks, tujuan, dan batasan project dalam satu dokumen."],[ListChecks,"Website checklist","Periksa hal penting sebelum website diluncurkan."],[BookOpenText,"Product guide","Panduan ringkas mengubah ide menjadi ruang lingkup yang bisa dikerjakan."]].map(([Icon,title,description])=><article key={String(title)} className="bg-emerald-50/50 p-8"><Icon className="h-8 w-8 text-emerald-700" weight="duotone"/><p className="mt-10 text-sm font-medium text-emerald-700">Segera tersedia</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.03em]">{String(title)}</h2><p className="mt-4 text-sm leading-6 text-slate-500">{String(description)}</p></article>)}</div>:<div className="grid gap-px overflow-hidden rounded-2xl border border-emerald-950/10 bg-emerald-950/10 md:grid-cols-2 lg:grid-cols-3">{resources.map(resource=>{const Icon=icons[resource.type]||FileText;return <article key={resource.id} className="flex min-h-[340px] flex-col bg-white p-8"><Icon className="h-8 w-8 text-emerald-700" weight="duotone"/><p className="mt-10 text-sm font-medium text-emerald-700">{resource.type}</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.03em]">{resource.title}</h2><p className="mt-4 flex-1 text-sm leading-6 text-slate-500">{resource.description}</p>{resource.fileUrl?<a href={resource.fileUrl} download className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-emerald-800">Unduh resource<ArrowDown className="h-4 w-4" weight="bold"/></a>:<span className="mt-8 text-sm text-slate-400">File belum tersedia</span>}</article>})}</div>}</div></section></main><SiteFooter/></div>}

