"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

interface ClientOption { id:string; companyName:string; }
interface ProjectOption { id:string; name:string; clientId:string; }
export function InvoiceCreateForm({clients,projects}:{clients:ClientOption[];projects:ProjectOption[]}){
  const router=useRouter();const {toast}=useToast();const [isSaving,setIsSaving]=useState(false);const [values,setValues]=useState({clientId:"",projectId:"none",amount:"",description:"",dueDate:"",status:"DRAFT"});
  const availableProjects=useMemo(()=>projects.filter(project=>project.clientId===values.clientId),[projects,values.clientId]);
  async function submit(event:React.FormEvent){event.preventDefault();setIsSaving(true);try{const response=await fetch("/api/v1/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,projectId:values.projectId==="none"?null:values.projectId})});const payload:unknown=await response.json();if(!response.ok){const message=typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Invoice gagal dibuat";throw new Error(message)}toast({title:"Invoice dibuat",description:"Invoice baru berhasil disimpan."});router.push("/invoices");router.refresh()}catch(error){toast({title:"Invoice gagal dibuat",description:error instanceof Error?error.message:"Silakan coba kembali.",variant:"destructive"})}finally{setIsSaving(false)}}
  const formattedAmount=values.amount?new Intl.NumberFormat("id-ID").format(Number(values.amount)):"";
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-emerald-950/10 bg-white p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Client" id="client"><Select value={values.clientId} onValueChange={value=>setValues({...values,clientId:value,projectId:"none"})} required><SelectTrigger id="client"><SelectValue placeholder="Pilih client"/></SelectTrigger><SelectContent>{clients.map(client=><SelectItem key={client.id} value={client.id}>{client.companyName}</SelectItem>)}</SelectContent></Select></Field><Field label="Project (opsional)" id="project"><Select value={values.projectId} onValueChange={value=>setValues({...values,projectId:value})} disabled={!values.clientId}><SelectTrigger id="project"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Tanpa project</SelectItem>{availableProjects.map(project=><SelectItem key={project.id} value={project.id}>{project.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Nominal" id="amount" helper={formattedAmount?`Rp ${formattedAmount}`:"Masukkan angka tanpa titik atau koma."}><div className="relative"><span className="pointer-events-none absolute inset-y-0 left-3 flex items-center text-sm font-medium text-slate-500">Rp</span><Input id="amount" type="text" inputMode="numeric" value={values.amount} onChange={e=>setValues({...values,amount:e.target.value.replace(/\D/g,"")})} required placeholder="15000000" className="pl-10" autoComplete="off"/></div></Field><Field label="Jatuh tempo" id="dueDate"><Input id="dueDate" type="date" value={values.dueDate} onChange={e=>setValues({...values,dueDate:e.target.value})} required/></Field><Field label="Status awal" id="status"><Select value={values.status} onValueChange={value=>setValues({...values,status:value})}><SelectTrigger id="status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="DRAFT">Draft</SelectItem><SelectItem value="UNPAID">Belum dibayar</SelectItem><SelectItem value="PARTIAL">Dibayar sebagian</SelectItem><SelectItem value="PAID">Lunas</SelectItem></SelectContent></Select></Field></div><Field label="Keterangan" id="description" helper="Tampil sebagai rincian singkat tujuan tagihan."><Textarea id="description" value={values.description} onChange={e=>setValues({...values,description:e.target.value})} maxLength={1000} rows={4} placeholder="Contoh: Termin pertama pengembangan website dan dashboard admin."/></Field><div className="flex justify-end gap-3 border-t border-emerald-950/10 pt-6"><Button type="button" variant="ghost" onClick={()=>router.back()}>Batal</Button><Button type="submit" loading={isSaving} disabled={clients.length===0}>Buat invoice</Button></div></form>
}
function Field({label,id,helper,children}:{label:string;id:string;helper?:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}{helper&&<p className="text-xs text-slate-500" aria-live="polite">{helper}</p>}</div>}
