"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

interface ClientOption { id: string; companyName: string; }
export function ProjectCreateForm({ clients }: { clients: ClientOption[] }) {
  const router=useRouter(); const {toast}=useToast(); const [isSaving,setIsSaving]=useState(false); const [values,setValues]=useState({name:"",description:"",clientId:"",deadline:"",priority:"MEDIUM"});
  async function submit(event:React.FormEvent){event.preventDefault();setIsSaving(true);try{const response=await fetch("/api/v1/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,deadline:values.deadline||null})});const payload:unknown=await response.json();if(!response.ok){const message=typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Project gagal dibuat";throw new Error(message)}if(typeof payload!=="object"||payload===null||!("id" in payload)||typeof payload.id!=="string")throw new Error("Respons server tidak valid");toast({title:"Project dibuat",description:`${values.name} berhasil ditambahkan.`});router.push(`/projects/${payload.id}`);router.refresh()}catch(error){toast({title:"Project gagal dibuat",description:error instanceof Error?error.message:"Silakan coba kembali.",variant:"destructive"})}finally{setIsSaving(false)}}
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-emerald-950/10 bg-white p-6 sm:p-8"><Field label="Nama project" id="name"><Input id="name" value={values.name} onChange={e=>setValues({...values,name:e.target.value})} required placeholder="Nama project"/></Field><Field label="Deskripsi" id="description"><Textarea id="description" value={values.description} onChange={e=>setValues({...values,description:e.target.value})} rows={5} placeholder="Tujuan dan ruang lingkup singkat"/></Field><div className="grid gap-5 sm:grid-cols-3"><Field label="Client" id="client"><Select value={values.clientId} onValueChange={value=>setValues({...values,clientId:value})} required><SelectTrigger id="client"><SelectValue placeholder="Pilih client"/></SelectTrigger><SelectContent>{clients.map(client=><SelectItem key={client.id} value={client.id}>{client.companyName}</SelectItem>)}</SelectContent></Select></Field><Field label="Prioritas" id="priority"><Select value={values.priority} onValueChange={value=>setValues({...values,priority:value})}><SelectTrigger id="priority"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="LOW">Low</SelectItem><SelectItem value="MEDIUM">Medium</SelectItem><SelectItem value="HIGH">High</SelectItem><SelectItem value="URGENT">Urgent</SelectItem></SelectContent></Select></Field><Field label="Deadline" id="deadline"><Input id="deadline" type="date" value={values.deadline} onChange={e=>setValues({...values,deadline:e.target.value})}/></Field></div>{clients.length===0&&<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Tambahkan client terlebih dahulu sebelum membuat project.</p>}<div className="flex justify-end gap-3 border-t border-emerald-950/10 pt-6"><Button type="button" variant="ghost" onClick={()=>router.back()}>Batal</Button><Button type="submit" loading={isSaving} disabled={clients.length===0}>Buat project</Button></div></form>
}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
