"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { AssetUpload } from "@/components/admin/asset-upload";

interface Field { key:string; label:string; placeholder?:string; type?:"text"|"url"|"textarea"|"select"|"image"|"file"; required?:boolean; options?:Array<{value:string;label:string}>; }
interface Props { endpoint:string; returnUrl:string; submitLabel:string; fields:Field[]; initialValues?:Record<string,string>; method?:"POST"|"PATCH"; }
export function RecordCreateForm({endpoint,returnUrl,submitLabel,fields,initialValues,method="POST"}:Props){const router=useRouter();const{toast}=useToast();const[values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(field=>[field.key,initialValues?.[field.key]??field.options?.[0]?.value??""])));const[isSaving,setIsSaving]=useState(false);async function submit(event:React.FormEvent){event.preventDefault();setIsSaving(true);try{const response=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const payload:unknown=await response.json();if(!response.ok){const message=typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Data gagal disimpan";throw new Error(message)}toast({title:"Data tersimpan",description:"Konten berhasil diperbarui."});router.push(returnUrl);router.refresh()}catch(error){toast({title:"Data gagal disimpan",description:error instanceof Error?error.message:"Silakan coba kembali.",variant:"destructive"})}finally{setIsSaving(false)}}return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-emerald-950/10 bg-white p-6 sm:p-8">{fields.map(field=><div key={field.key} className="space-y-2"><Label htmlFor={field.key}>{field.label}</Label>{field.type==="image"||field.type==="file"?<AssetUpload value={values[field.key]} onChange={value=>setValues({...values,[field.key]:value})} kind={field.type} required={field.required} label={field.placeholder}/>:field.type==="textarea"?<Textarea id={field.key} value={values[field.key]} onChange={e=>setValues({...values,[field.key]:e.target.value})} required={field.required} rows={field.key==="content"?10:4} placeholder={field.placeholder}/>:field.type==="select"?<Select value={values[field.key]} onValueChange={value=>setValues({...values,[field.key]:value})}><SelectTrigger id={field.key}><SelectValue/></SelectTrigger><SelectContent>{field.options?.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select>:<Input id={field.key} type={field.type==="url"?"url":"text"} value={values[field.key]} onChange={e=>setValues({...values,[field.key]:e.target.value})} required={field.required} placeholder={field.placeholder}/>}</div>)}<div className="flex justify-end gap-3 border-t border-emerald-950/10 pt-6"><Button type="button" variant="ghost" onClick={()=>router.back()}>Batal</Button><Button type="submit" loading={isSaving}>{submitLabel}</Button></div></form>}
