"use client";

import { useEffect, useState } from "react";
import { useTheme } from "next-themes";
import { Bell, Globe, Key, Palette, Shield, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

interface SettingsPanelProps { user:{name:string;email:string;role:string}; }
const preferencesKey="jhiro-admin-preferences";
export function SettingsPanel({user}:SettingsPanelProps){const{toast}=useToast();const{theme,setTheme}=useTheme();const[name,setName]=useState(user.name);const[isSaving,setIsSaving]=useState(false);const[passwords,setPasswords]=useState({currentPassword:"",newPassword:"",confirmPassword:""});const[prefs,setPrefs]=useState({emailNotifications:true,projectUpdates:true,invoiceReminders:true,systemAnnouncements:true,compactMode:false,animations:true,language:"id",timezone:"Asia/Jakarta",currency:"IDR"});
useEffect(()=>{const stored=window.localStorage.getItem(preferencesKey);if(stored){try{const parsed:unknown=JSON.parse(stored);if(typeof parsed==="object"&&parsed!==null)setPrefs(current=>({...current,...parsed}))}catch{window.localStorage.removeItem(preferencesKey)}}},[]);
async function request(body:Record<string,string>){setIsSaving(true);try{const response=await fetch("/api/v1/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload:unknown=await response.json();if(!response.ok){const message=typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Pengaturan gagal disimpan";throw new Error(message)}toast({title:"Pengaturan tersimpan",description:"Perubahan akun berhasil diterapkan."});return true}catch(error){toast({title:"Pengaturan gagal disimpan",description:error instanceof Error?error.message:"Silakan coba kembali.",variant:"destructive"});return false}finally{setIsSaving(false)}}
function savePreferences(){window.localStorage.setItem(preferencesKey,JSON.stringify(prefs));toast({title:"Preferensi tersimpan",description:"Pengaturan perangkat ini berhasil diperbarui."})}
async function updatePassword(){if(passwords.newPassword!==passwords.confirmPassword){toast({title:"Password tidak cocok",description:"Konfirmasi password baru harus sama.",variant:"destructive"});return}const saved=await request({action:"password",currentPassword:passwords.currentPassword,newPassword:passwords.newPassword});if(saved)setPasswords({currentPassword:"",newPassword:"",confirmPassword:""})}
return <div className="space-y-7"><div><h1>Settings</h1><p className="mt-2 text-muted-foreground">Kelola akun, keamanan, dan preferensi workspace.</p></div><Tabs defaultValue="profile" className="space-y-6"><TabsList className="max-w-full justify-start overflow-x-auto"><Tab value="profile" icon={User}>Profile</Tab><Tab value="notifications" icon={Bell}>Notifications</Tab><Tab value="security" icon={Shield}>Security</Tab><Tab value="appearance" icon={Palette}>Appearance</Tab><Tab value="localization" icon={Globe}>Localization</Tab></TabsList>
<TabsContent value="profile"><Panel title="Profile settings" description="Kelola informasi dasar akun Anda."><div className="grid gap-5 sm:grid-cols-2"><Field label="Nama" id="name"><Input id="name" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email" id="email"><Input id="email" value={user.email} disabled/></Field><Field label="Role" id="role"><Input id="role" value={user.role} disabled/></Field></div><Button loading={isSaving} onClick={()=>request({action:"profile",name})}>Simpan perubahan</Button></Panel></TabsContent>
<TabsContent value="notifications"><Panel title="Notification settings" description="Pilih notifikasi yang ingin diterima.">{[["emailNotifications","Email notifications","Terima notifikasi melalui email"],["projectUpdates","Project updates","Perubahan penting pada project"],["invoiceReminders","Invoice reminders","Pengingat invoice jatuh tempo"],["systemAnnouncements","System announcements","Informasi dari sistem"]].map(([key,label,description],index)=><div key={key}>{index>0&&<Separator className="mb-5"/>}<Toggle label={label} description={description} checked={prefs[key as keyof typeof prefs]===true} onCheckedChange={checked=>setPrefs({...prefs,[key]:checked})}/></div>)}<Button onClick={savePreferences}>Simpan preferensi</Button></Panel></TabsContent>
<TabsContent value="security"><Panel title="Security settings" description="Perbarui password untuk menjaga keamanan akun."><Field label="Password saat ini" id="current"><Input id="current" type="password" value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Password baru" id="new"><Input id="new" type="password" minLength={8} value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></Field><Field label="Konfirmasi password" id="confirm"><Input id="confirm" type="password" minLength={8} value={passwords.confirmPassword} onChange={e=>setPasswords({...passwords,confirmPassword:e.target.value})}/></Field></div><Button loading={isSaving} onClick={updatePassword}><Key className="mr-2 h-4 w-4"/>Update password</Button><Separator/><Toggle label="Two-factor authentication" description="Fitur ini memerlukan provider OTP dan belum diaktifkan." checked={false} disabled onCheckedChange={()=>undefined}/></Panel></TabsContent>
<TabsContent value="appearance"><Panel title="Appearance" description="Sesuaikan tampilan workspace pada perangkat ini."><Toggle label="Dark mode" description="Gunakan tema gelap" checked={theme==="dark"} onCheckedChange={checked=>setTheme(checked?"dark":"light")}/><Separator/><Toggle label="Compact mode" description="Kurangi jarak antar elemen" checked={prefs.compactMode} onCheckedChange={checked=>setPrefs({...prefs,compactMode:checked})}/><Separator/><Toggle label="Activity animations" description="Tampilkan animasi transisi" checked={prefs.animations} onCheckedChange={checked=>setPrefs({...prefs,animations:checked})}/><Button onClick={savePreferences}>Simpan preferensi</Button></Panel></TabsContent>
<TabsContent value="localization"><Panel title="Localization" description="Atur bahasa dan format regional pada perangkat ini."><div className="grid gap-5 sm:grid-cols-3"><SelectField label="Language" value={prefs.language} onValueChange={value=>setPrefs({...prefs,language:value})} options={[["id","Bahasa Indonesia"],["en","English"]]}/><SelectField label="Timezone" value={prefs.timezone} onValueChange={value=>setPrefs({...prefs,timezone:value})} options={[["Asia/Jakarta","WIB"],["Asia/Makassar","WITA"],["Asia/Jayapura","WIT"]]}/><SelectField label="Currency" value={prefs.currency} onValueChange={value=>setPrefs({...prefs,currency:value})} options={[["IDR","IDR"],["USD","USD"]]}/></div><Button onClick={savePreferences}>Simpan preferensi</Button></Panel></TabsContent></Tabs></div>}
function Tab({value,icon:Icon,children}:{value:string;icon:typeof User;children:React.ReactNode}){return <TabsTrigger value={value}><Icon className="mr-2 h-4 w-4"/>{children}</TabsTrigger>}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="space-y-6">{children}</CardContent></Card>}
function Field({label,id,children}:{label:string;id:string;children:React.ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Toggle({label,description,checked,onCheckedChange,disabled}:{label:string;description:string;checked:boolean;onCheckedChange:(checked:boolean)=>void;disabled?:boolean}){return <div className="flex items-center justify-between gap-4"><div><Label>{label}</Label><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onCheckedChange} disabled={disabled}/></div>}
function SelectField({label,value,onValueChange,options}:{label:string;value:string;onValueChange:(value:string)=>void;options:string[][]}){return <div className="space-y-2"><Label>{label}</Label><Select value={value} onValueChange={onValueChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([option,labelText])=><SelectItem key={option} value={option}>{labelText}</SelectItem>)}</SelectContent></Select></div>}
